NEUBURG-30: Add config for smpt, database url
digitalfabrik/wohnraumboerse-backend pull request #6
Opened 2018-05-15 08:12 UTC by maxammann

2018-05-17 18:37 UTC, NKlug commented on .vscode/settings.json
> +}
Do we want this Visual Studio Code file in the repo?

2018-05-17 19:08 UTC, maxammann commented on .vscode/settings.json
> +}
Yes, this configures some useful/needed plugins of vscode

2018-05-18 20:29 UTC, NKlug approved these changes

2018-05-18 21:26 UTC, steffenkleinle requested changes
https://github.com/Integreat/neuburg-backend/pull/6/files?utf8=%E2%9C%93&diff=unified#diff-453452d78c4c37b73382bc89a66d51cbR39
smtp config missing in const mailService = new MailService()

2018-05-19 08:51 UTC, maxammann commented
@klinzo done

2018-05-19 09:28 UTC, steffenkleinle approved these changes

2018-05-19 15:34 UTC, michael-markl approved these changes

2018-05-19 15:34 UTC, Schedulaar commented on src/services/OfferService.js
> +      .populate({ path: 'formData', select: '-_id -__v' })
Is it forced, to have new lines when starting '.' (probably only when they overflow)?
I think the structure was better before.

2018-05-19 15:49 UTC, merged